### ISSUE TITLE
Prevent a user from queuing in a bot while participating in a match

### ISSUE THREAD

**Issue by FF5Ninjaa** [shub-wub/ShadowrunBot#18]
- Removing the ability to queue while already in a match will prevent users from skipping the queue line as well as preventing any potential issues with a bot firing despite one of the queued players being in a match already
- Potential implementation: don't allow a user to queue until a match has been scored

**Comment by bryman360** [comment]
Not sure if this would be a potential issue: Sometimes matches get cancelled and, when they do, I believe they get someone to 'delete' the match. I'm not sure if they are actually deleting it or just removing the bot's message. If they just remove the message, then the players from that match might get caught in 'limbo'. They can't score the game (since the message is gone) but they also can't queue back up since they would be considered 'in a match'.

One solution I can think of is to have a '/deleteMatch' command for admins/mods. It could allow a more formal match deletion that clears the players from being considered in a match. You could print out the matchMessageId (or a hash of it) at the top of the bot's match message as a "Match #" and then run /deleteMatch <Match #> and the bot could handle the rest. Then implement this feature so they can't queue up unless the match is scored or the match is deleted.

**Comment by shub-wub** [comment]
I am not sure that it actually presents the issue but its worth looking in to. Instead of a delete command I am pretty sure we can grab the delete event of the message and just trigger the database clean up logic off of that. Should be implemented for both deletes matches and deleted queues.

**Comment by bryman360** [comment]
Makes sense. I'm not familiar with discord's event listeners. From some brief searching, one issue would be if the bot is ever offline and the message is deleted. The event would not trigger the cleanup process and would require manual searching/deleting. 

But since the bot seems to always be on, this is really an edge case that doesn't seem like it'd really be an issue. Would require the bot to go down mid match and someone to delete the match before it comes back online. I definitely like the event listener better.
